<a href="https://colab.research.google.com/github/rutiknarute/Pytorch-Bucket/blob/main/Pytorch_Bucket.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

In [2]:
import torch
import numpy as np

In [3]:
my_list=[[1,3,5,6,0], [4,7,3,7,9]]
print(my_list)
type(my_list)

[[1, 3, 5, 6, 0], [4, 7, 3, 7, 9]]


list

In [4]:
np1= np.random.rand(3,4)
print(np1)

[[0.88932842 0.91753692 0.64295391 0.05266132]
 [0.56205906 0.59369663 0.16245939 0.13312627]
 [0.54757974 0.9066949  0.88861887 0.49803147]]


In [5]:
np1.dtype

dtype('float64')

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.2930,  0.0254,  0.5249, -0.7708],
        [ 0.6957, -0.2569,  0.4230, -1.0359],
        [ 0.3618, -1.6893,  0.0350, -0.3650]])

In [7]:
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d.dtype
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
tensor_3d.dtype

torch.float32

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8893, 0.9175, 0.6430, 0.0527],
        [0.5621, 0.5937, 0.1625, 0.1331],
        [0.5476, 0.9067, 0.8886, 0.4980]], dtype=torch.float64)

In [11]:
my_tor= torch.arange(15)

In [12]:
my_tor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
my_tor = my_tor.reshape(3,-1)
my_tor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [14]:

tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor (Vector):")
print(tensor_1d)
print()

1D Tensor (Vector):
tensor([1, 2, 3])



In [15]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

element = tensor[1, 0]
print(f"Indexed Element (Row 1, Column 0): {element}")
slice_tensor = tensor[:2, :]
print(f"Sliced Tensor (First two rows): \n{slice_tensor}")

Indexed Element (Row 1, Column 0): 3
Sliced Tensor (First two rows): 
tensor([[1, 2],
        [3, 4]])


In [16]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(tensor)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [17]:
reshaped_tensor= tensor.view(2,3)

In [18]:
reshaped_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
tensor_a = torch.tensor( [[3,4,-8],[7,8,-4]])
tensor_b = torch.tensor([10,9,21])
c = tensor_a + tensor_b
print(c)

tensor([[13, 13, 13],
        [17, 17, 17]])


In [20]:
de = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"using device: {de}")

using device: cuda


In [21]:
tensor_size = (10000, 10000)
a = torch.randn(tensor_size, device=de)
b = torch.randn(tensor_size, device=de)

In [22]:
c=a+b

In [23]:
c

tensor([[-1.0150, -1.1516, -0.7323,  ...,  0.3295,  0.3368, -0.6850],
        [-1.1733, -1.6686, -0.0530,  ...,  2.7904,  1.1629,  2.0066],
        [-1.7728, -0.2196, -0.2642,  ...,  2.4629,  0.9808, -2.0877],
        ...,
        [ 1.6924,  0.0453, -1.1390,  ...,  0.5779, -1.4749,  0.1443],
        [-1.7129,  1.2596,  0.1893,  ...,  1.6171,  1.5158, -3.2407],
        [ 0.6495, -0.4368,  0.1024,  ..., -0.5812,  0.7834, -0.4322]],
       device='cuda:0')

In [24]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch[7]

tensor(7)

In [30]:
my_torch8=my_torch.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [46]:
my_torch8[:,0]

tensor([0, 2, 4, 6, 8])